set autoindent
set smartindent
syntax on
set number
set laststatus=2
set statusline=%F%m%r%h%w\ [%{&ff}][\%03.3b=\%02.2B]\%=%04l/%04L,%04v[%03p%%]
set backspace=2
set shiftwidth=2
set tabstop=2
set softtabstop=2
set expandtab
set smarttab
set fileformats=unix,dos,mac
set encoding=utf-8
set fileencoding=utf-8
set ignorecase
set wrapscan
set hlsearch
set listchars=eol:\ ,trail:-,tab:>-
